# permissions for end users to view clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfig-viewer-role
rules:
- apiGroups:
  - k0s.k0sproject.io
  resources:
  - clusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k0s.k0sproject.io
  resources:
  - clusterconfigs/status
  verbs:
  - get
