# permissions for end users to edit clusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfig-editor-role
rules:
- apiGroups:
  - k0s.k0sproject.io
  resources:
  - clusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0s.k0sproject.io
  resources:
  - clusterconfigs/status
  verbs:
  - get
